# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iHunterModel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
        migrations.AddField(
            model_name='student',
            name='educational_organizations',
            field=models.ManyToManyField(to='iHunterModel.EducationalOrganization'),
        ),
    ]
