# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iHunterModel', '0002_auto_20170521_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iHunterModel.Person')),
                ('educational_organizations', models.ManyToManyField(to='iHunterModel.EducationalOrganization')),
            ],
            options={
                'abstract': False,
            },
            bases=('iHunterModel.person',),
        ),
    ]
