# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iHunterModel', '0004_auto_20170517_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iHunterModel.Title'),
        ),
    ]
