# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iHunterModel', '0005_auto_20170517_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(default='uploads/images/logos/default/organization.jpg', upload_to='uploads/images/logos/')),
                ('test_field', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
