# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iHunterModel', '0006_educationalorganization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalorganization',
            name='logo',
            field=models.ImageField(default='uploads/images/logos/default/organization.png', upload_to='uploads/images/logos/'),
        ),
    ]
