# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iHunterModel', '0007_auto_20170517_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalOrganizationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='educationalorganization',
            name='test_field',
        ),
        migrations.AddField(
            model_name='educationalorganization',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iHunterModel.EducationalOrganizationType'),
        ),
        migrations.AddField(
            model_name='educationalorganization',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iHunterModel.OrganizationType'),
        ),
    ]
