# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iHunterModel', '0008_auto_20170517_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalorganization',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
