# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iHunterModel', '0009_auto_20170517_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iHunterModel.Gender'),
        ),
    ]
